"""add projects and manager department relation

Revision ID: 36578ff6d948
Revises: dd9855edd273
Create Date: 2026-05-19 14:40:48.193859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36578ff6d948'
down_revision: Union[str, Sequence[str], None] = 'dd9855edd273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objectif', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_debut_prevue', sa.Date(), nullable=True),
    sa.Column('date_fin_prevue', sa.Date(), nullable=True),
    sa.Column('cout_estime', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.Column('exercice_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['exercice_id'], ['exercices_budgetaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projets_code'), 'projets', ['code'], unique=True)
    op.create_index(op.f('ix_projets_id'), 'projets', ['id'], unique=False)
    op.add_column('budgets', sa.Column('projet_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'budgets', ['projet_id'])
    op.create_foreign_key(None, 'budgets', 'projets', ['projet_id'], ['id'])
    op.add_column('users', sa.Column('departement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'departements', ['departement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'departement_id')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_constraint(None, 'budgets', type_='unique')
    op.drop_column('budgets', 'projet_id')
    op.drop_index(op.f('ix_projets_id'), table_name='projets')
    op.drop_index(op.f('ix_projets_code'), table_name='projets')
    op.drop_table('projets')
    # ### end Alembic commands ###
