"""create all tables in database

Revision ID: dd9855edd273
Revises: 
Create Date: 2026-05-18 07:27:44.080006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9855edd273'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_budgetaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_categorie', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('departements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('exercices_budgetaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_role', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom_role')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('montant_total_prevu', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('montant_total_realise', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ecart_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.Column('exercice_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['exercice_id'], ['exercices_budgetaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_reference'), 'budgets', ['reference'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type_notification', sa.String(length=50), nullable=True),
    sa.Column('est_lue', sa.Boolean(), nullable=True),
    sa.Column('date_envoi', sa.DateTime(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('lignes_budgetaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('montant_prevu', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('montant_realise', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ecart_montant', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ecart_pourcentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type_ligne', sa.String(length=50), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories_budgetaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapports_budgetaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('type_rapport', sa.String(length=100), nullable=False),
    sa.Column('periode_debut', sa.Date(), nullable=True),
    sa.Column('periode_fin', sa.Date(), nullable=True),
    sa.Column('date_generation', sa.DateTime(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validations_budgetaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statut_validation', sa.String(length=50), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecarts_budgetaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montant_prevu', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('montant_realise', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ecart_montant', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ecart_pourcentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nature_ecart', sa.String(length=50), nullable=True),
    sa.Column('niveau_alerte', sa.String(length=50), nullable=True),
    sa.Column('commentaire_analyse', sa.Text(), nullable=True),
    sa.Column('ligne_budgetaire_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ligne_budgetaire_id'], ['lignes_budgetaires.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ligne_budgetaire_id')
    )
    op.create_table('previsions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montant_prevu', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date_prevision', sa.Date(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('ligne_budgetaire_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ligne_budgetaire_id'], ['lignes_budgetaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montant_realise', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date_realisation', sa.Date(), nullable=False),
    sa.Column('reference_piece', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_realisation', sa.String(length=50), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('ligne_budgetaire_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ligne_budgetaire_id'], ['lignes_budgetaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses_ecarts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('consequence', sa.Text(), nullable=True),
    sa.Column('recommandation', sa.Text(), nullable=True),
    sa.Column('date_analyse', sa.DateTime(), nullable=True),
    sa.Column('ecart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecart_id'], ['ecarts_budgetaires.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecart_id')
    )
    op.create_table('actions_correctives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('analyse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analyse_id'], ['analyses_ecarts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actions_correctives')
    op.drop_table('analyses_ecarts')
    op.drop_table('realisations')
    op.drop_table('previsions')
    op.drop_table('ecarts_budgetaires')
    op.drop_table('validations_budgetaires')
    op.drop_table('rapports_budgetaires')
    op.drop_table('lignes_budgetaires')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_budgets_reference'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('exercices_budgetaires')
    op.drop_table('departements')
    op.drop_table('categories_budgetaires')
    # ### end Alembic commands ###
